/**
 * Trillet AI API Integration — AllTheCalls
 *
 * Confirmed working endpoints (as of Apr 2026):
 *   GET    /v1/api/agents        — list all agents in workspace
 *   GET    /v1/api/agents/:id    — get a single agent
 *   POST   /v1/api/agents        — create a new agent
 *   PUT    /v1/api/agents/:id    — update an agent
 *   DELETE /v1/api/agents/:id    — delete an agent
 *   GET    /v1/api/call-history  — list call history (500s when empty — Trillet bug)
 *
 * Phone number provisioning is dashboard-only — assign numbers to agents
 * via app.trillet.ai, then record the assigned number in your client DB.
 *
 * Sub-accounts / reseller billing: does not exist in Trillet API.
 * Use Stripe for client billing (handled in /api/checkout).
 */

require("dotenv").config();

const BASE_URL = "https://api.trillet.ai";

function getHeaders() {
  const key = process.env.TRILLET_API_KEY;
  const workspaceId = process.env.TRILLET_WORKSPACE_ID;
  if (!key) throw new Error("TRILLET_API_KEY not set");
  if (!workspaceId) throw new Error("TRILLET_WORKSPACE_ID not set");
  return {
    "Content-Type": "application/json",
    "x-api-key": key,
    "x-workspace-id": workspaceId,
  };
}

async function apiRequest(method, path, body = null) {
  const res = await fetch(`${BASE_URL}${path}`, {
    method,
    headers: getHeaders(),
    body: body ? JSON.stringify(body) : undefined,
  });

  const text = await res.text();
  let data;
  try { data = JSON.parse(text); } catch { data = { raw: text }; }

  if (!res.ok) {
    throw new Error(`Trillet ${method} ${path} → ${res.status}: ${text.slice(0, 200)}`);
  }
  return data;
}

/** List all agents in the workspace. */
async function listAgents() {
  return apiRequest("GET", "/v1/api/agents");
}

/** Get a single agent by ID. */
async function getAgent(agentId) {
  return apiRequest("GET", `/v1/api/agents/${agentId}`);
}

/**
 * Create a new AI receptionist agent for a client.
 * @param {object} config
 * @param {string} config.name      — e.g. "Sarah Johnson — Compass (AllTheCalls)"
 */
async function createAgent(config) {
  return apiRequest("POST", "/v1/api/agents", {
    name: config.name,
    llmModel: config.llmModel || "gemini-2.5-flash",
    ttsModel: {
      provider: "rime",
      voiceId: "arcana_celeste",
      language: "en",
    },
    settings: { model: "arcana", speed: 1.05 },
    type: "voice",
  });
}

/** Update an existing agent. */
async function updateAgent(agentId, updates) {
  return apiRequest("PUT", `/v1/api/agents/${agentId}`, updates);
}

/** Delete an agent. */
async function deleteAgent(agentId) {
  return apiRequest("DELETE", `/v1/api/agents/${agentId}`);
}

/**
 * Get call history for the workspace.
 * Note: Trillet returns 500 when there are zero calls — known bug. Returns [] safely.
 */
async function getCallHistory(options = {}) {
  try {
    const params = new URLSearchParams();
    if (options.agentId) params.set("agentId", options.agentId);
    if (options.page) params.set("page", String(options.page));
    if (options.limit) params.set("limit", String(options.limit));
    const query = params.toString() ? `?${params}` : "";
    return await apiRequest("GET", `/v1/api/call-history${query}`);
  } catch (err) {
    if (err.message.includes("500")) return [];
    throw err;
  }
}

/**
 * Onboard a new AllTheCalls client.
 * Creates their AI agent. Phone number must then be assigned via app.trillet.ai.
 *
 * @param {object} client
 * @param {string} client.name
 * @param {string} client.brokerage
 * @param {string} client.greeting  — generated by claude-personas.js
 */
async function onboardClient(client) {
  const agentName = `${client.name}${client.brokerage ? ` — ${client.brokerage}` : ""} (AllTheCalls)`;
  const agent = await createAgent({ name: agentName });
  return {
    agentId: agent._id,
    agentName: agent.name,
    status: agent.status,
    phoneNumber: null,
    note: `Agent created. Go to app.trillet.ai → Telephony → assign a phone number to agent ID: ${agent._id}`,
  };
}

module.exports = { listAgents, getAgent, createAgent, updateAgent, deleteAgent, getCallHistory, onboardClient };
